export type StatusFilter =
  | "all"
  | "idea"
  | "in development"
  | "MVP Ready"
  | "Recruiting"
  | "Refactoring";

export const FILTER_OPTIONS: { value: StatusFilter; label: string }[] = [
  { value: "all", label: "All" },
  { value: "idea", label: "Idea" },
  { value: "in development", label: "In development" },
  { value: "MVP Ready", label: "MVP Ready" },
  { value: "Recruiting", label: "Recruiting" },
  { value: "Refactoring", label: "Refactoring" },
];

const TECH_OPTIONS = [
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C#",
  "C++",
  "C",
  "Go",
  "Rust",
  "Swift",
  "Kotlin",
  "Dart",
  "PHP",
  "Ruby",
  "Scala",
  "R",
  "MATLAB",
  "Perl",
  "Haskell",
  "Elixir",
  "Erlang",
  "Clojure",
  "F#",
  "Objective-C",
  "Lua",
  "Shell",
  "PowerShell",
  "React",
  "Vue.js",
  "Angular",
  "Svelte",
  "Next.js",
  "Nuxt.js",
  "Gatsby",
  "Remix",
  "Astro",
  "Solid.js",
  "Ember.js",
  "Backbone.js",
  "jQuery",
  "Bootstrap",
  "Tailwind CSS",
  "Material-UI",
  "Chakra UI",
  "Ant Design",
  "Styled Components",
  "Sass",
  "Less",
  "Webpack",
  "Vite",
  "Parcel",
  "Rollup",
  "Node.js",
  "Express",
  "NestJS",
  "Fastify",
  "Koa",
  "Django",
  "Flask",
  "FastAPI",
  "Spring",
  "Spring Boot",
  "Laravel",
  "Symfony",
  "CodeIgniter",
  "Ruby on Rails",
  "Sinatra",
  "ASP.NET",
  "ASP.NET Core",
  "Phoenix",
  "Gin",
  "Echo",
  "Fiber",
  "Actix",
  "Rocket",
  "React Native",
  "Flutter",
  "Ionic",
  "Xamarin",
  "NativeScript",
  "Cordova",
  "PhoneGap",
  "SwiftUI",
  "Jetpack Compose",
  "Unity",
  "Unreal Engine",
  "Godot",
  "CryEngine",
  "GameMaker Studio",
  "Construct",
  "Phaser",
  "PixiJS",
  "Three.js",
  "Babylon.js",
  "Cocos2d",
  "LibGDX",
  "PostgreSQL",
  "MySQL",
  "MongoDB",
  "Redis",
  "SQLite",
  "MariaDB",
  "Oracle",
  "SQL Server",
  "Cassandra",
  "CouchDB",
  "Neo4j",
  "Elasticsearch",
  "DynamoDB",
  "Firebase",
  "Supabase",
  "PlanetScale",
  "CockroachDB",
  "InfluxDB",
  "TimescaleDB",
  "AWS",
  "Azure",
  "Google Cloud",
  "Docker",
  "Kubernetes",
  "Terraform",
  "Ansible",
  "Jenkins",
  "GitLab CI",
  "GitHub Actions",
  "CircleCI",
  "Travis CI",
  "Vagrant",
  "Puppet",
  "Chef",
  "Prometheus",
  "Grafana",
  "ELK Stack",
  "Splunk",
  "TensorFlow",
  "PyTorch",
  "Keras",
  "Scikit-learn",
  "Pandas",
  "NumPy",
  "OpenCV",
  "Hugging Face",
  "Jupyter",
  "MLflow",
  "Weights & Biases",
  "Apache Spark",
  "Apache Kafka",
  "Solidity",
  "Web3.js",
  "Ethers.js",
  "Hardhat",
  "Truffle",
  "Foundry",
  "Ethereum",
  "Polygon",
  "Solana",
  "IPFS",
  "The Graph",
  "GraphQL",
  "REST API",
  "gRPC",
  "WebSocket",
  "Socket.io",
  "Apollo",
  "Prisma",
  "TypeORM",
  "Sequelize",
  "Mongoose",
  "Drizzle",
  "tRPC",
  "Jest",
  "Mocha",
  "Cypress",
  "Playwright",
  "Selenium",
  "Puppeteer",
  "Vitest",
  "Testing Library",
  "JUnit",
  "Pytest",
  "Git",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "Jira",
  "Confluence",
  "Figma",
  "Adobe XD",
  "Sketch",
  "Postman",
  "Insomnia",
  "Vercel",
  "Netlify",
  "Heroku",
  "Railway",
  "Render",
  "Cloudflare",
  "Nginx",
  "Apache",
  "Linux",
  "Windows",
  "macOS",
  "Ubuntu",
  "Debian",
  "CentOS",
];

const ROLE_OPTIONS = [
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "Mobile Developer",
  "iOS Developer",
  "Android Developer",
  "React Native Developer",
  "Flutter Developer",
  "Game Developer",
  "Unity Developer",
  "Unreal Engine Developer",
  "Web Developer",
  "Desktop Application Developer",
  "Embedded Systems Developer",
  "Firmware Developer",
  "API Developer",
  "Blockchain Developer",
  "Smart Contract Developer",
  "Web3 Developer",
  "Solidity Developer",
  "UI Designer",
  "UX Designer",
  "UX/UI Designer",
  "Product Designer",
  "Graphic Designer",
  "Visual Designer",
  "Interaction Designer",
  "Motion Designer",
  "3D Designer",
  "Game Designer",
  "Level Designer",
  "Character Designer",
  "UI/UX Researcher",
  "Design System Designer",
  "Brand Designer",
  "Illustrator",
  "Software Engineer",
  "Senior Software Engineer",
  "Lead Software Engineer",
  "Principal Engineer",
  "Software Architect",
  "System Architect",
  "Cloud Architect",
  "Solution Architect",
  "Enterprise Architect",
  "DevOps Engineer",
  "Site Reliability Engineer (SRE)",
  "Platform Engineer",
  "Infrastructure Engineer",
  "Security Engineer",
  "Cybersecurity Engineer",
  "Penetration Tester",
  "Security Analyst",
  "Network Engineer",
  "Database Administrator",
  "Database Engineer",
  "Data Scientist",
  "Data Engineer",
  "Data Analyst",
  "Business Intelligence Analyst",
  "Machine Learning Engineer",
  "MLOps Engineer",
  "AI Engineer",
  "Deep Learning Engineer",
  "Computer Vision Engineer",
  "NLP Engineer",
  "Data Architect",
  "Big Data Engineer",
  "Analytics Engineer",
  "Product Manager",
  "Senior Product Manager",
  "Product Owner",
  "Technical Product Manager",
  "Product Designer",
  "Product Marketing Manager",
  "Project Manager",
  "Technical Project Manager",
  "Program Manager",
  "Engineering Manager",
  "Engineering Director",
  "CTO",
  "VP of Engineering",
  "Head of Engineering",
  "QA Engineer",
  "QA Automation Engineer",
  "Test Engineer",
  "Software Tester",
  "Manual Tester",
  "Performance Test Engineer",
  "Security Tester",
  "Test Architect",
  "QA Lead",
  "Quality Assurance Manager",
  "Technical Writer",
  "Technical Documentation Writer",
  "Content Writer",
  "Technical Content Creator",
  "Developer Advocate",
  "Developer Relations",
  "Technical Evangelist",
  "Technical Marketing",
  "Scrum Master",
  "Agile Coach",
  "Product Owner",
  "Release Manager",
  "Change Manager",
  "Business Analyst",
  "Technical Business Analyst",
  "Systems Analyst",
  "Requirements Analyst",
  "Product Analyst",
  "Data Analyst",
  "Financial Analyst",
  "Operations Analyst",
  "Blockchain Developer",
  "Smart Contract Developer",
  "Cryptocurrency Developer",
  "AR/VR Developer",
  "AR Developer",
  "VR Developer",
  "IoT Developer",
  "Embedded Developer",
  "Firmware Engineer",
  "Hardware Engineer",
  "Robotics Engineer",
  "Automation Engineer",
  "Technical Consultant",
  "Software Consultant",
  "IT Consultant",
  "Freelance Developer",
  "Contract Developer",
  "Independent Contractor",
  "Engineering Lead",
  "Tech Lead",
  "Team Lead",
  "Development Lead",
  "Architecture Lead",
  "Platform Lead",
  "Engineering Director",
  "Head of Product",
  "Head of Design",
  "Head of Data",
  "Technical Support Engineer",
  "Customer Success Engineer",
  "Solutions Engineer",
  "Sales Engineer",
  "Pre-Sales Engineer",
  "Implementation Engineer",
  "Integration Engineer",
  "Support Engineer",
  "Research Engineer",
  "Research Scientist",
  "Innovation Engineer",
  "R&D Engineer",
  "Algorithm Engineer",
  "Performance Engineer",
  "Scalability Engineer",
  "Reliability Engineer",
  "Compliance Engineer",
  "Accessibility Engineer",
  "SEO Engineer",
  "Growth Engineer",
  "Marketing Engineer",
];

export const UNIQUE_TECH_OPTIONS = Array.from(new Set(TECH_OPTIONS));
export const UNIQUE_ROLE_OPTIONS = Array.from(new Set(ROLE_OPTIONS));
